### PR TITLE
initial implementation

### PR DESCRIPTION
**Pull request by richm**
This is the initial implementation - it passes CI testing but
I had to disable mypy
There are unit tests for the hook functions.

To Do:
* Allow the local tox.ini to delete a setting from the default

### CODE REVIEW

**Comment by richm** [comment]
Re: coverage - here are the only two places in the code that are not covered by the unit tests:
```
try:
    from tox.config import ParseIni as ToxParseIni  # tox 3.4.0+
except ImportError:
    from tox.config import parseini as ToxParseIni
```
I think this was copied from the tox-ansible plugin.  I suppose we could say that we only support the latest tox - I'll note that the latest Fedora 32 version of tox  is 3.15.2

```
            if not prop_is_set(envconf, propname):
                try:
                    setattr(envconf, propname, getattr(def_envconf, propname))
                except AttributeError:  # some props cannot be set
                    pass
```
We just skip properties that cannot be set - there are a couple of properties in the environment config in tox which are implemented in such a way that they cannot be set.

It doesn't seem worth it to test these - otoh I guess I need to investigate how to mark these as "do not need coverage" or some such

**Comment by nhosoi** [comment]
@richm, sorry, a stupid question. Could you please tell me how to use the tox-lsr plugins?
I checked out pr/2 and just ran tox in tox-lsr, then these 3 tests failed.
```
ERROR:   black: commands failed
ERROR:   isort: commands failed
ERROR:   flake8: commands failed
```
I guess some operations are needed prior to the command line? E.g., setup.py??? If you could share any instructions, I'd appreciate it.

**Comment by richm** [comment]
> @richm, sorry, a stupid question. Could you please tell me how to use the tox-lsr plugins?
> I checked out pr/2 and just ran tox in tox-lsr, then these 3 tests failed.
> 
> ```
> ERROR:   black: commands failed
> ERROR:   isort: commands failed
> ERROR:   flake8: commands failed
> ```
> 
> I guess some operations are needed prior to the command line? E.g., setup.py??? If you could share any instructions, I'd appreciate it.

If you have cloned this PR locally, do `python setup.py install --user` - once you are done, use `pip uninstall tox-lsr`

**Comment by nhosoi** [comment]
Thank you, @richm.
> If you have cloned this PR locally, do `python setup.py install --user` - once you are done, use `pip uninstall tox-lsr`

There's still something wrong in my testing...
```
$ git branch
  main
* pr/2
(tox_env) $ pip list | egrep tox-lsr
tox-lsr         0.0.1
```
But I get tons of ERRORs, e.g.,
```
ERROR: InvocationError for command /usr/bin/bash /home/nhosoi/linux-system-roles/tox-lsr/tox_env/lib64/python3.8/site-packages/tox_lsr-0.0.1-py3.8.egg/tox_lsr/data/test_scripts/runflake8.sh . (exited with code 127)
8< snip >8
ERROR:   py38-pylint: commands failed
ERROR:   py36-flake8: commands failed
ERROR:   ans28-py36-pytest: could not install deps [-rpytest_requirements.txt, -ransible_requirements.txt, ansible==2.8.*, jinja2==2.7.*]; v = InvocationError("/home/nhosoi/linux-system-roles/tox-lsr/.tox/ans28-py36-pytest/bin/python -m pip install -rpytest_requirements.txt -ransible_requirements.txt 'ansible==2.8.*' 'jinja2==2.7.*'", 1)
```
Actually, I don't have `test_scripts` in tox_lsr/data...
```
$ ls tox_env/lib64/python3.8/site-packages/tox_lsr-0.0.1-py3.8.egg/tox_lsr/data
ansible_requirements.txt  pytest_requirements.txt  tox-default.ini
```

**Comment by richm** [comment]
Try the latest commit
Note that there are still a few problems e.g. we will have to implement support for getting the tool settings from the tox.ini format to a local file and merging it with the settings from tox-default.ini - the settings in `[flake8]` in tox-default.ini are currently ignored, which means you will see a lot of flake8 issues.
The main thing I wanted with this PR was to get reviews for the python code

**Comment by richm** [comment]
If you want to try it out - see https://github.com/linux-system-roles/kernel_settings/pull/38 for an example of how I converted the kernel_settings role to use this.

network looks something like this (incomplete):
```ini
# SPDX-License-Identifier: MIT
[lsr_config]
lsr_enable = true

[lsr_yamllint]
configfile = .yamllint.yml
configbasename = .yamllint.yml

[lsr_ansible-lint]
configfile = .ansible-lint

[testenv]
setenv =
    RUN_PYLINT_EXCLUDE = ^(\..*|ensure_provider_tests\.py|print_all_options\.py)$
    RUN_PYTEST_SETUP_MODULE_UTILS = true
    RUN_PYLINT_SETUP_MODULE_UTILS = true
    RUN_PYTEST_EXTRA_ARGS = -v
    RUN_FLAKE8_EXTRA_ARGS = --exclude tests/ensure_provider_tests.py,scripts/print_all_options.py,tests/network/ensure_provider_tests.py,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg
    LSR_PUBLISH_COVERAGE = normal
```

**Comment by richm** [comment]
not sure why coveralls failed - problem connecting to `coveralls.io`?

**Comment by richm** [comment]
note that a lot of the 'ugliness' in the code is because we have to support both tox 2 and tox 3 - https://travis-ci.com/github/linux-system-roles/network/jobs/434766629 - `  Downloading https://files.pythonhosted.org/packages/1d/4e/20c679f8c5948f7c48591fde33d442e716af66a31a88f5791850a75041eb/tox-2.9.1-py2.py3-none-any.whl (73kB)` - I'm assuming we have to use tox 2.x because of having to support python 2.6, which is because we have to support managing EL6 hosts which use python 2.6, which means we need to ensure the python code runs on that platform.

**Comment by richm** [comment]
I have also verified that the plugin works with logging https://github.com/linux-system-roles/logging/pull/187/ and with certificate https://github.com/linux-system-roles/certificate/pull/69

I don't really want to proceed any further until we can come to a consensus that this is the right approach.

**Comment by richm** [comment]
I'm going to merge this if there are no objections

**Pull request merged**
