### PR TITLE
support batch-file, batch-report and other enhancements

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by nhosoi** [comment]
My test has started working! (with one issue :).

If I put `--skip-tags tests::nvme` or `--skip-tags=tests::nvme` like this, the ansible-playbook fails with the cryptic error in the `ansible.log` file below. Please note that the file ` /tmp/tmp6b4dcvq9.yml` is cleaned up when the test is done. So, I haven't had a chance to examine the contents... The problem does not occur if I put `--skip-tags tests::nvme` in the batch file. I wonder if the temporary file is generated by standard-inventory-qcow2? If so, are there any way to keep it and check how and why it's broken?
```
python3 runqemu.py --config=NONE --cache=/tmp/tmp.rE5genAj4r \
--inventory=/usr/share/ansible/inventory/standard-inventory-qcow2 \
--image-file=/tmp/tmp.rE5genAj4r/image.qcow2    --skip-tags tests::nvme \
--batch-file kdump_batch.txt
```
ansible.log
```
ansible-playbook [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: ANSIBLE_CALLBACK_WHITELIST option, normalizing names to 
new standard, use ANSIBLE_CALLBACKS_ENABLED instead. This feature will be 
removed from ansible-core in version 2.15. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
ERROR! Completely failed to parse inventory source /tmp/tmp6b4dcvq9.yml
```

**Comment by richm** [comment]
1) the ansible arguments (like `--skip-tags`) should come *after* all of the runqemu.py arguments (it should still work if not, but it makes it easier to read)
2) if you specify ansible arguments on the command line, and no playbooks, you must specify `--` as the last argument - runqemu can't tell the difference between an ansible argument and a playbook otherwise - so this should work:
```
python3 runqemu.py --config=NONE --cache=/tmp/tmp.rE5genAj4r \
--inventory=/usr/share/ansible/inventory/standard-inventory-qcow2 \
--image-file=/tmp/tmp.rE5genAj4r/image.qcow2   \
--batch-file kdump_batch.txt  --skip-tags tests::nvme --
```

**Comment by richm** [comment]
For batch files, you could also put the ansible arguments in the batch file instead of the command line like this:
```
--log-file=something --skip-tags tests::nvme -- tests/tests_some_test.yml
```
you still have to use the `--` to separate the ansible arguments from the playbooks

**Comment by nhosoi** [comment]
By adding `--` at the end of the arguments for `runqemu.py`, it worked perfectly with --skip-tags in the command-line. Thanks a lot, @richm!

> For batch files, you could also put the ansible arguments in the batch file instead of the command line like this:
> 
> ```
> --log-file=something --skip-tags tests::nvme -- tests/tests_some_test.yml
> ```
> 
> you still have to use the `--` to separate the ansible arguments from the playbooks

Yes, that was clear from the example in README.md. Regarding adding `--` to the command line, it'd be nice if such command-line examples are found in README.md, as well. :)

Other than that, lgtm.

**Comment by richm** [comment]
@nhosoi how about this: https://github.com/linux-system-roles/tox-lsr/pull/73/commits/0bc8bd4c2cf11aa95fc18286849c0adf75eee1e3

**Comment by nhosoi** [comment]
> @nhosoi how about this: [0bc8bd4](https://github.com/linux-system-roles/tox-lsr/commit/0bc8bd4c2cf11aa95fc18286849c0adf75eee1e3)

Great! Thanks a lot, @richm!

**Review by nhosoi — APPROVED** [review]
lgtm

**Pull request merged**
