### PR TITLE
ansible-test executed in the collection test requires rstcheck module.

### PR DESCRIPTION
**Pull request by nhosoi**

### CODE REVIEW

**Review by richm — APPROVED** [review]
lgtm

**Comment by richm** [comment]
> lgtm

. . . but you'll also need to add `rstcheck` to tests/fixtures/test_tox_merge_ini/result.ini so that the tests will pass

**Comment by nhosoi** [comment]
> > lgtm
> 
> . . . but you'll also need to add `rstcheck` to tests/fixtures/test_tox_merge_ini/result.ini so that the tests will pass

The rstcheck test is run in ansible-test launched in runcollection.sh here. The result is treated as part of the collection test. Is the result checking still needed?
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/runcollection.sh#L49

**Comment by richm** [comment]
> Is the result checking still needed?

I mean the tox tests for tox-lsr itself.  If you run `tox` locally you will see the same failures as are in the github checks for this PR.

**Comment by nhosoi** [comment]
> > Is the result checking still needed?
> 
> I mean the tox tests for tox-lsr itself. If you run `tox` locally you will see the same failures as are in the github checks for this PR.

Ah, I see... I didn't know that... Once I added rstcheck ti result.ini, the errors disappeared.  Updating this pr. Thank you!!

**Comment by nhosoi** [comment]
Thank, @richm. Merging this pr.

**Pull request merged**
